# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  default:
    desc: Display all available commands
    cmd: task --list

  lint:
    desc: Run linters across the source code.
    dir: server
    cmd: golangci-lint run ./...
